# If use policy_pickup.onnx, then set default joint pos of joint6 to 1.57.
policy_path: "exported_policy/b2wz1_plb_loco_manipulation/policy_pickup_v2.onnx"
xml_path: "unitree_robots/b2wz1/ground.xml"

simulation_duration: 180.0
simulation_dt: 0.005
control_decimation: 4

startup_hold_s: 1.0
startup_blend_s: 2.0

history_length: 5
obs_dim_per_step: 80
obs_dim: 400
action_dim: 22

base_command: [0.0, 0.0, 0.0]

root_pos: [0.0, 0.0, 0.6017]
root_quat_wxyz: [1.0, 0.0, 0.0, 0.0]

default_joint_pos: [
   0.1, 0.8, -1.5, 0.0,
  -0.1, 0.8, -1.5, 0.0,
   0.1, 1.0, -1.5, 0.0,
  -0.1, 1.0, -1.5, 0.0,
   0.0, 1.48, -1.0, -0.54, 0.0, 1.57, 0.0
]

kps: [
  200.0, 200.0, 300.0,  0.0,
  200.0, 200.0, 300.0,  0.0,
  200.0, 200.0, 300.0,  0.0,
  200.0, 200.0, 300.0,  0.0,
   76.8, 115.2,  89.6,  76.8, 76.8, 76.8, 76.8
]

kds: [
   8.0, 8.0, 12.0, 10.0,
   8.0, 8.0, 12.0, 10.0,
   8.0, 8.0, 12.0, 10.0,
   8.0, 8.0, 12.0, 10.0,
   4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0
]

leg_action_scale: 0.25
arm_action_scale: [0.10, 0.10, 0.10, 0.10, 0.10, 0.10]

# Arm target rate limiter.
# If true, policy arm action is first converted to raw joint-position target:
#   raw_arm_target = default_arm_pos + blend * arm_action_scale * arm_action
# Then the final arm target sent to the PD controller is limited by:
#   arm_target[t] = arm_target[t-1] + clip(raw - prev, +/- arm_target_rate_limit * control_dt)
# Unit: rad/s, order: [joint1, joint2, joint3, joint4, joint5, joint6]
enable_arm_target_rate_limit: true
arm_target_rate_limit: [0.20, 0.20, 0.20, 0.20, 0.20, 0.20]

wheel_action_scale: 4.0

leg_torque_limits: [
  200.0, 200.0, 320.0,
  200.0, 200.0, 320.0,
  200.0, 200.0, 320.0,
  200.0, 200.0, 320.0
]

arm_torque_limits: [30.0, 60.0, 30.0, 30.0, 30.0, 30.0]
gripper_torque_limit: 30.0
wheel_velocity_limits: [50.0, 50.0, 50.0, 50.0]

ee_body: "gripperStator"
ee_command_mode: "direct"
ee_command_path: "utilities/data/keypoints_plb_pickup.npy"

# PLB frame:
#   origin = [base_x, base_y, ee_ground_z]
#   orientation = yaw-only(base_quat)
ee_ground_z: 0.0

ee_kp_dx: 0.30
ee_kp_dz: 0.30
ee_command_seed: 0
ee_cycle_duration_s: 8.0

ee_sequential_traj_duration_s: 2.0
ee_sequential_hold_duration_s: 1.0

vis_ee_target: true
vis_ee_target_axis_len: 0.20
vis_ee_target_axis_radius: 0.01
vis_ee_target_sphere_size: 0.03
vis_ee_target_alpha: 0.9
vis_ee_target_show_current: true
